// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tniniethoqoyyblgegeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuaW5pZXRob3FveXlibGdlZ2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NjEzMTksImV4cCI6MjA1NTMzNzMxOX0.XfAKwpcD-ClTLe8a3-8slTVMBSZ9Th2oC7zzKyo2UgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);