// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkcvxkninkcidknibcbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrY3Z4a25pbmtjaWRrbmliY2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NzYwNTksImV4cCI6MjA1MjE1MjA1OX0.nfwaAP98BOy-LpyX2H5hTzOE6dpfihOj82GfipOJv6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);